### ISSUE TITLE
[BUG] Sometime when you manage to go fullscreen before the player is replaced, then, after it is replaced the fullscreen button no longer work

### ISSUE THREAD

**Issue by ale5000-git** [Andrews54757/FastStream#181]
**Describe the bug**
Sometime when you manage to go fullscreen before the player is replaced, then, after it is replaced the fullscreen button no longer work.

**Version**
1.3.13

**Platform**
Chrome

**Steps to Reproduce**
Sometime when you manage to go fullscreen before the player is replaced, then, after it is replaced the fullscreen button no longer work.
Sample url: `ok.ru/videoembed/6934036482656`

Here are some errors that I see:
```
BackgroundUtils.mjs:4 Unable to send message 'init' {message: 'The message port closed before a response was received.'}message: "The message port closed before a response was received."[[Prototype]]: Object
checkMessageError @ BackgroundUtils.mjs:4
(anonime) @ background.mjs:340
okHtml5Player.min.js:6 Uncaught TypeError: Cannot read properties of null (reading 'contains')
    at Object.r [as isElementInDocument] (okHtml5Player.min.js:6:2959)
    at okHtml5Player.min.js:3:20444
    at Array.forEach (<anonymous>)
    at e (okHtml5Player.min.js:3:20404)
    at okHtml5Player.min.js:3:23003
r @ okHtml5Player.min.js:6
(anonime) @ okHtml5Player.min.js:3
e @ okHtml5Player.min.js:3
(anonime) @ okHtml5Player.min.js:3

BackgroundUtils.mjs:4 Unable to send message 'init' {message: 'The message port closed before a response was received.'}message: "The message port closed before a response was received."[[Prototype]]: Objectconstructor: ƒ ()[[Prototype]]: Object
checkMessageError @ BackgroundUtils.mjs:4
(anonime) @ background.mjs:340
okHtml5Player.min.js:6 Uncaught TypeError: Cannot read properties of null (reading 'contains')
    at Object.r [as isElementInDocument] (okHtml5Player.min.js:6:2959)
    at okHtml5Player.min.js:3:20444
    at Array.forEach (<anonymous>)
    at e (okHtml5Player.min.js:3:20404)
    at okHtml5Player.min.js:3:23003
r @ okHtml5Player.min.js:6
(anonime) @ okHtml5Player.min.js:3
e @ okHtml5Player.min.js:3
(anonime) @ okHtml5Player.min.js:3

BackgroundUtils.mjs:4 Unable to send message 'fullscreen_change' {message: 'The message port closed before a response was received.'}message: "The message port closed before a response was received."[[Prototype]]: Object
checkMessageError @ BackgroundUtils.mjs:4
(anonime) @ background.mjs:277
VideoAnalyzer.mjs:76 [VideoAnalyzer] Loading analyzer data
6okHtml5Player.min.js:6 Uncaught TypeError: Cannot read properties of null (reading 'contains')
    at Object.r [as isElementInDocument] (okHtml5Player.min.js:6:2959)
    at okHtml5Player.min.js:3:20444
    at Array.forEach (<anonymous>)
    at e (okHtml5Player.min.js:3:20404)
    at okHtml5Player.min.js:3:23003
r @ okHtml5Player.min.js:6
(anonime) @ okHtml5Player.min.js:3
e @ okHtml5Player.min.js:3
(anonime) @ okHtml5Player.min.js:3
VideoAnalyzer.mjs:76 [VideoAnalyzer] Loading analyzer data
6okHtml5Player.min.js:6 Uncaught TypeError: Cannot read properties of null (reading 'contains')
    at Object.r [as isElementInDocument] (okHtml5Player.min.js:6:2959)
    at okHtml5Player.min.js:3:20444
    at Array.forEach (<anonymous>)
    at e (okHtml5Player.min.js:3:20404)
    at okHtml5Player.min.js:3:23003
r @ okHtml5Player.min.js:6
(anonime) @ okHtml5Player.min.js:3
e @ okHtml5Player.min.js:3
(anonime) @ okHtml5Player.min.js:3

BackgroundUtils.mjs:4 Unable to send message 'sendFrameId' {message: 'The message port closed before a response was received.'}message: "The message port closed before a response was received."[[Prototype]]: Object
checkMessageError @ BackgroundUtils.mjs:4
(anonime) @ background.mjs:376
```

**Comment by Andrews54757** [comment]
Nothing I can do about that as it is part of the browser's security features. Don't go into fullscreen before the player is replaced.
