### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by AliMardanTalpur** [Andrews54757/FastStream#230]
TypeError: Cannot read properties of undefined (reading 'equalizerNodes')
TypeError: Cannot read properties of undefined (reading 'equalizerNodes')
at chrome-extension://kkeakohpadmbldjaiggikmnldlfkdfog/player/ui/audio/AudioChannelMixer.mjs:425:43
at Function.from (<anonymous>)
at AudioChannelMixer.setupNodes (chrome-extension://kkeakohpadmbldjaiggikmnldlfkdfog/player/ui/audio/AudioChannelMixer.mjs:411:31)
at AudioConfigManager.setupNodes (chrome-extension://kkeakohpadmbldjaiggikmnldlfkdfog/player/ui/audio/AudioConfigManager.mjs:359:28)
at FastStreamClient.setSource (chrome-extension://kkeakohpadmbldjaiggikmnldlfkdfog/player/FastStreamClient.mjs:527:33)
at async FastStreamClient.addSource (chrome-extension://kkeakohpadmbldjaiggikmnldlfkdfog/player/FastStreamClient.mjs:449:7)

**Comment by Andrews54757** [comment]
see #228
