### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by southsxint** [Andrews54757/FastStream#231]
**Describe the bug**
Please send this error to the developer at https://github.com/Andrews54757/FastStream/issues
TypeError: Cannot read properties of undefined (reading 'equalizerNodes')
TypeError: Cannot read properties of undefined (reading 'equalizerNodes')
at chrome-extension://kkeakohpadmbldjaiggikmnldlfkdfog/player/ui/audio/AudioChannelMixer.mjs:425:43
at Function.from (<anonymous>)
at AudioChannelMixer.setupNodes (chrome-extension://kkeakohpadmbldjaiggikmnldlfkdfog/player/ui/audio/AudioChannelMixer.mjs:411:31)
at AudioConfigManager.setupNodes (chrome-extension://kkeakohpadmbldjaiggikmnldlfkdfog/player/ui/audio/AudioConfigManager.mjs:359:28)
at FastStreamClient.setSource (chrome-extension://kkeakohpadmbldjaiggikmnldlfkdfog/player/FastStreamClient.mjs:527:33)
at async FastStreamClient.addSource (chrome-extension://kkeakohpadmbldjaiggikmnldlfkdfog/player/FastStreamClient.mjs:449:7)

**Version**
FastStream version  1.3.24

**Platform**
Chrome

**Steps to Reproduce**
https://ww7.solarmovie.to/movie/mayor-of-kingstown-season-3-1630857142.html

**Comment by lu4nS** [comment]
i could get it solved by reinstalling

**Comment by WolfganP** [comment]
https://github.com/Andrews54757/FastStream/issues/228 fixed in v1.3.25
