### ISSUE TITLE
toptions is not defined error after video contrast is changed

### ISSUE THREAD

**Issue by ken16416** [Andrews54757/FastStream#88]
**Describe the bug**
Increasing the brightness only works in the first video, then on the second one the extension just wont work and a message error appear.

                               ### *************************** The message**********************************
Please send this error to the developer at https://github.com/Andrews54757/FastStream/issues
toptions is not defined
ReferenceError: toptions is not defined
at CSSFilterUtils.getFilterString (chrome-extension://kkeakohpadmbldjaiggikmnldlfkdfog/player/utils/CSSFilterUtils.mjs:18:32)
at FastStreamClient.updateCSSFilters (chrome-extension://kkeakohpadmbldjaiggikmnldlfkdfog/player/FastStreamClient.mjs:194:38)
at FastStreamClient.setSource (chrome-extension://kkeakohpadmbldjaiggikmnldlfkdfog/player/FastStreamClient.mjs:347:12)
at async FastStreamClient.addSource (chrome-extension://kkeakohpadmbldjaiggikmnldlfkdfog/player/FastStreamClient.mjs:305:7)

**Version**
Version v1.2.23

**Platform**
Google Chrome
Windows 10
WEBSITE: animewave.to

**Steps to Reproduce**
Add the extension with default values, change the brightness to double or +150% on the first video, then change to a new video and boom error message will popup.

**Comment by Andrews54757** [comment]
Fixed. It was caused by a typo. Set the contrast to 100% to fix it before the next release.
